import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const titleFont = localFont({
  src: "/fonts/queen_of_melbourne.ttf",
  variable: "--font-titleFont",
  weight: "100 900",
});
const genFont = localFont({
  src: "/fonts/FixelDisplay-Regular.ttf",
  variable: "--font-genFont",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Yukapoly",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${titleFont.variable} ${genFont.variable} antialiased`}
      >
      {children}
      </body>
      </html>
  );
}
