import ErrorRedirectWrapper from '@/components/custom/ErrorRedirectWrapper';
import { ermilovFont, genFont, namuFont, titleFont } from '@/config/fonts';
import { Providers } from '@/providers/providers';
import '@/styles/globals.css';
import clsx from 'clsx';
import type { Metadata, Viewport } from 'next';
import GatewayError from './(home)/rooms/_components/GatewayError';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: [{ media: '(prefers-color-scheme: light)', color: 'white' }],
}; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={clsx(
          'font-sans antialiased',
          'bg-primaryGame',
          genFont.variable,
          titleFont.variable,
          ermilovFont.variable,
          namuFont.variable,
        )}
      >
        <Providers>
          <GatewayError />
          <ErrorRedirectWrapper>{children}</ErrorRedirectWrapper>
        </Providers>
      </body>
    </html>
  );
}
