export const emitWithAck = ['getVisibleGames', 'getGameData'] as const;
export const emitWithoutAck = [
  'createGame',
  'joinGame',
  'leaveGame',
  'rollDice',
  'payToBankForSpecialField',
  'payToUserForSecret',
  'payToBankForSecret',
  'payForPrivateField',
  'putUpForAuction',
  'raisePrice',
  'refuseAuction',
  'buyField',
  'passTurn',
  'buyBranch',
  'sellBranch',
  'surrender',
  'mortgageField',
  'newMessage',
  'onMessage',
  'newGameMessage',
  'chatData',
  'mutualChatData',
  'unmortgageField',
] as const;
export const listenEvents = [
  'onMessage',
  'gameChatMessage',
  'rejoin',
  'gameData',
  'newGameCreated',
  'onParticipateGame',
  'updatePlayers',
  'updateGameData',
  'playerSurrendered',
] as const;
