export const emitWithAck = ['getVisibleGames', 'getGameData'] as const;
export const emitWithoutAck = [
  'createGame',
  'joinGame',
  'leaveGame',
  'rollDice',
  'payToBankForSpecialField',
  'payToUserForSecret',
  'payToBankForSecret',
  'payForPrivateField',
  'putUpForAuction',
  'raisePrice',
  'refuseAuction',
  'buyField',
  'passTurn',
  'buyBranch',
  'sellBranch',
  'surrender',
  'mortgageField',
  'newMessage',
  'onMessage',
  'newGameMessage',
  'chatData',
  'mutualChatData',
  'unmortgageField',
  'payForField',
  'payRedemptionForField',
  'refuseFromTrade',
  'acceptTrade',
  'offerTrade',
] as const;
export const listenEvents = [
  'error',
  'onMessage',
  'gameChatMessage',
  'rejoin',
  'gameData',
  'newGameCreated',
  'onParticipateGame',
  'updatePlayers',
  'updateGameData',
  'playerSurrendered',
  'tradeOffered',
  'playerWon',
  'raisedPrice',
  'rolledDice',
  'refusedFromAuction',
  'passTurnToNext',
  'secret',
  'hasPutUpForAuction',
  'clearStartedGame',
  'startGame',
] as const;
