import type { Metadata, Viewport } from 'next';
import '@/styles/globals.css';
import { Providers } from '../../providers/providers';
import clsx from 'clsx';
import { Navbar } from '@/components/navbar';
import { genFont, titleFont } from '@/config/fonts';
import GatewayError from './rooms/_components/GatewayError';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: [{ media: '(prefers-color-scheme: light)', color: 'white' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={clsx(
          'relative min-h-screen bg-primaryGame font-sans antialiased',
          genFont.variable,
          titleFont.variable,
        )}
      >
        <Providers>
          <div className="relative flex flex-col">
            <Navbar />
            <main className="w-full pt-16">{children}</main>
            <GatewayError />
          </div>
        </Providers>
      </body>
    </html>
  );
}
