import type { Metadata, Viewport } from 'next';
import '@/styles/globals.css';
import { Providers } from '@/providers/providers';
import clsx from 'clsx';
import { genFont, titleFont } from '@/config/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: [{ media: '(prefers-color-scheme: light)', color: 'white' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={clsx(
          'min-h-screen font-sans antialiased light',
          'bg-primary',
          'text-white',
          genFont.variable,
          titleFont.variable,
        )}
      >
        <Providers>
          <main className="h-screen w-full pl-24 pr-14">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
